# Generated by Django 5.0.2 on 2024-03-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_fb',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.BigIntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contact_fb',
            },
        ),
        migrations.CreateModel(
            name='Register_user',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phonenumber', models.BigIntegerField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Register_user',
            },
        ),
    ]
